name: Windows Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Make Windows Installer
        run: npx electron-forge make --platform win32 --arch x64

      - name: List built files
        run: dir out\make\squirrel.windows\x64

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: fileflow-installer
          path: out/make/squirrel.windows/x64/*.exe
